version: 2.1

defaults: &defaults
  working_directory: ~/service
  docker:
    - image: circleci/node:14.15.5

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm run build
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - persist_to_workspace:
          root: ~/
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: npm run test
          environment:
            CIRCLE_BRANCH: local
            JEST_JUNIT_OUTPUT_DIR: ./junit.xml
      - store_artifacts:
          path: ./coverage

workflows:
  build-test:
    jobs:
      - build:
          name: build-dev
          context: dev
          filters:
            branches:
              ignore:
                - main
      - build:
          name: build-prod
          context: prod
          filters:
            branches:
              only:
                - main
      - test:
          name: test-dev
          context: dev
          filters:
            branches:
              ignore:
                - main
          requires:
            - build-dev
      - test:
          name: test-prod
          context: prod
          requires:
            - build-prod
          filters:
            branches:
              only:
                - main